@startuml
left to right direction
skin rose

' TODO: Add the domain model

class Socio {
    - NUMERO_LIBROS_MAXIMO: int
    - nombre: String
    - apellido: String
    - correoElectronico: String
    - numeroDeSocio: int
    - contrasenia: String
    - librosEnPrestamo: Libro[]
    + Socio(nombre: String, apellido: String, correoElectronico: String, numeroDeSocio: int, contrasenia: String)
    + getNombre(): String
    + getApellido(): String
    + getNombreCompleto(): String
    + getCorreoElectronico(): String
    + getNumeroDeSocio(): int
    + getContrasenia(): String
    + agregarLibro(libro: Libro): void
    + setContrasenia(contrasenia: String): void
    + setCorreoElectronico(correoElectronico: String): void
}
class Libro {
    -isbn: String
    -titulo: String
    -autor: String
    -categoria: String
    -calificacion: float
    -numeroCalificaciones: float

    +Libro(isbn: String, titulo: String, autor: String, categoria: String, calificacion: float, numeroCalificaciones: float)
    +getIsbn(): String
    +getTitulo(): String
    +getAutor(): String
    +getCategoria(): String
    +getCalificacion(): float
    +setCalificacion(calificacion: float): void
    +getNumeroCalificaciones(): float
    +setNumeroCalificaciones(numeroCalificaciones: float): void
}
    Class Sistema {
    -Socio[] Socio
    -Libro[] Libro
    +iniciarSession(numeroDeSocio : int contrasenia String): void
    +cerrarSession(): void
    +realizarPrestamoLibro(): isbn: String
    +obtegerCatalogoLibros(): String
    -buscarLibro(): Libro
    -cargarInformacion(): void
    guardarInformacion(): void
    obtenerDatosSocioLogeado(): String
    +contraseniaCambiada(): Boolean
    +correoCambiado(): Boolean
    +calificacionLibro(): Boolean
}


Socio"1" <- "1"Sistema : Registra
Libro"1" <-- "1"Sistema : Registra
Socio"1" -> "0..5"Libro: Pide

@enduml
